version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db
    image: php:7.3-apache
    container_name: php73
    volumes: 
      - ./src:/var/www/html/
    ports:
      - 8080:80
    environment:
      - HOST=db
      - DATABASE=test_db
      - USER=root
      - PASS=root
      - SECRET_KEY=prtimes
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports: 
     - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
        MYSQL_ROOT_PASSWORD: root
